### PR TITLE
Fix prop warning at RemoveUserDialog

### LINKED ISSUE #88: Fix prop validation of RemoveUserDialog
This is shown when you access `/institution/details` route
screenshot from 2018-10-20 04-01-50

### PR DESCRIPTION
**Pull request by igorbrasileiro**
Fix #88

### CODE REVIEW

File: src/components/InstitutionPage/DetailsPage/EmployeeList.js [hunk 1]
```diff
@@ -139,11 +141,12 @@ class EmployeeList extends Component {
             A instituição não possui {headTitle.toLowerCase()}
           </Typography>
         }
-        <RemoveUserDialog
-          onClose={this.handleRemoveUserDialogToggle}
-          open={openDialog}
-          userId={userId}
-        />
+        {selectedInstitution > -1
```
Comment (Klynger) [inline src/components/InstitutionPage/DetailsPage/EmployeeList.js]: `selectedInstitution` is a string
